/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_diegozelaya;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) agregar_arma.getModel();
        model.addElement(new Armas("Hacha",0));
        model.addElement(new Armas("Pistola",0));
        model.addElement(new Armas("Bate",0));
        model.addElement(new Armas("Pala",0));
        model.addElement(new Armas("Sierra Electrica",0));
        model.addElement(new Armas("Punos",0));
        
        agregar_arma.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Estadistica = new javax.swing.JTabbedPane();
        Agregar = new javax.swing.JPanel();
        NombreLabel = new javax.swing.JLabel();
        agregar_edad = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        agregar_nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        agregar_sexoM = new javax.swing.JRadioButton();
        agregar_sexoF = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agregar_tipoC = new javax.swing.JRadioButton();
        agregar_tipoY = new javax.swing.JRadioButton();
        agregar_tipoS = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        agregar_estadoV = new javax.swing.JRadioButton();
        agregar_estadoD = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        agregar_desaparecidos = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        agregar_dano = new javax.swing.JTextField();
        agregar_arma = new javax.swing.JComboBox<>();
        Estadisticas = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTextArea();
        Modificar = new javax.swing.JPanel();
        Agregar1 = new javax.swing.JPanel();
        NombreLabel1 = new javax.swing.JLabel();
        agregar_edad1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        agregar_nombre1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        agregar_sexoM1 = new javax.swing.JRadioButton();
        agregar_sexoF1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        agregar_tipoC1 = new javax.swing.JRadioButton();
        agregar_tipoY1 = new javax.swing.JRadioButton();
        agregar_tipoS1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        agregar_estadoV1 = new javax.swing.JRadioButton();
        agregar_estadoD1 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        agregar_desaparecidos1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        agregar_dano1 = new javax.swing.JTextField();
        agregar_arma1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        Eliminar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NombreLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NombreLabel.setText("Nombre");

        agregar_edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        agregar_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_edadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Edad");

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Sexo");

        buttonGroup1.add(agregar_sexoM);
        agregar_sexoM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_sexoM.setText("Masculino");
        agregar_sexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_sexoMActionPerformed(evt);
            }
        });

        buttonGroup1.add(agregar_sexoF);
        agregar_sexoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_sexoF.setText("Femenino");
        agregar_sexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_sexoFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Arma");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Tipo");

        buttonGroup2.add(agregar_tipoC);
        agregar_tipoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_tipoC.setText("Campista");
        agregar_tipoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_tipoCActionPerformed(evt);
            }
        });

        buttonGroup2.add(agregar_tipoY);
        agregar_tipoY.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_tipoY.setText("YeizonBorjis");

        buttonGroup2.add(agregar_tipoS);
        agregar_tipoS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_tipoS.setText("Supervisor");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Desaparecio");

        buttonGroup3.add(agregar_estadoV);
        agregar_estadoV.setText("Vivo");
        agregar_estadoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_estadoVActionPerformed(evt);
            }
        });

        buttonGroup3.add(agregar_estadoD);
        agregar_estadoD.setText("Desaparecido");
        agregar_estadoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_estadoDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Estado");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Dano");

        agregar_arma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hacha", "pistola", "bate", "pala", "sierra eléctrica", "puno" }));

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar);
        Agregar.setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(agregar_tipoS)
                                .addGap(31, 31, 31)
                                .addComponent(agregar_tipoC))
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(agregar_estadoV)
                                .addGap(18, 18, 18)
                                .addComponent(agregar_estadoD)))
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(agregar_desaparecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(agregar_tipoY)))))
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel5))
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreLabel)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(agregar_nombre)
                                .addComponent(agregar_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AgregarLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(agregar_sexoM)
                                    .addGap(29, 29, 29)
                                    .addComponent(agregar_sexoF)))
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addComponent(agregar_arma, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27)
                                .addComponent(agregar_dano, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(421, 421, 421))
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreLabel)
                    .addComponent(agregar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar_edad))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agregar_sexoM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_sexoF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregar_arma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar_dano))
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_tipoS)
                    .addComponent(agregar_tipoC)
                    .addComponent(agregar_tipoY))
                .addGap(33, 33, 33)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_estadoV)
                    .addComponent(agregar_estadoD)
                    .addComponent(agregar_desaparecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Estadistica.addTab("Agregar", Agregar);

        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        lista.setColumns(20);
        lista.setRows(5);
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout EstadisticasLayout = new javax.swing.GroupLayout(Estadisticas);
        Estadisticas.setLayout(EstadisticasLayout);
        EstadisticasLayout.setHorizontalGroup(
            EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticasLayout.createSequentialGroup()
                .addGroup(EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstadisticasLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EstadisticasLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        EstadisticasLayout.setVerticalGroup(
            EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstadisticasLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        Estadistica.addTab("Estadistica", Estadisticas);

        NombreLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NombreLabel1.setText("Nombre");

        agregar_edad1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        agregar_edad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_edad1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Edad");

        jButton3.setText("Guardar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Sexo");

        buttonGroup1.add(agregar_sexoM1);
        agregar_sexoM1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_sexoM1.setSelected(true);
        agregar_sexoM1.setText("Masculino");
        agregar_sexoM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_sexoM1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(agregar_sexoF1);
        agregar_sexoF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_sexoF1.setText("Femenino");
        agregar_sexoF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_sexoF1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Arma");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Tipo");

        buttonGroup2.add(agregar_tipoC1);
        agregar_tipoC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_tipoC1.setText("Campista");
        agregar_tipoC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_tipoC1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(agregar_tipoY1);
        agregar_tipoY1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_tipoY1.setText("YeizonBorjis");

        buttonGroup2.add(agregar_tipoS1);
        agregar_tipoS1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregar_tipoS1.setSelected(true);
        agregar_tipoS1.setText("Supervisor");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Desaparecio");

        buttonGroup3.add(agregar_estadoV1);
        agregar_estadoV1.setSelected(true);
        agregar_estadoV1.setText("Vivo");
        agregar_estadoV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_estadoV1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(agregar_estadoD1);
        agregar_estadoD1.setText("Desaparecido");
        agregar_estadoD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_estadoD1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Estado");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Dano");

        agregar_arma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hacha", "pistola", "bate", "pala", "sierra eléctrica", "puno" }));

        jLabel15.setText("Posicion");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        javax.swing.GroupLayout Agregar1Layout = new javax.swing.GroupLayout(Agregar1);
        Agregar1.setLayout(Agregar1Layout);
        Agregar1Layout.setHorizontalGroup(
            Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar1Layout.createSequentialGroup()
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Agregar1Layout.createSequentialGroup()
                        .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Agregar1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(agregar_tipoS1)
                                .addGap(31, 31, 31)
                                .addComponent(agregar_tipoC1))
                            .addGroup(Agregar1Layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(agregar_estadoV1)
                                .addGap(18, 18, 18)
                                .addComponent(agregar_estadoD1)))
                        .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Agregar1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(agregar_desaparecidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Agregar1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(agregar_tipoY1)))))
                    .addGroup(Agregar1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel13))
                    .addGroup(Agregar1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreLabel1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Agregar1Layout.createSequentialGroup()
                                .addComponent(agregar_arma1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel14)
                                .addGap(27, 27, 27)
                                .addComponent(agregar_dano1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Agregar1Layout.createSequentialGroup()
                                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agregar_nombre1)
                                    .addComponent(agregar_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Agregar1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(agregar_sexoM1)
                                        .addGap(29, 29, 29)
                                        .addComponent(agregar_sexoF1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Agregar1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Agregar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(421, 421, 421))
        );
        Agregar1Layout.setVerticalGroup(
            Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Agregar1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreLabel1)
                    .addComponent(agregar_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar_edad1))
                .addGap(18, 18, 18)
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(agregar_sexoM1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_sexoF1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregar_arma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar_dano1))
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addGap(17, 17, 17)
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_tipoS1)
                    .addComponent(agregar_tipoC1)
                    .addComponent(agregar_tipoY1))
                .addGap(33, 33, 33)
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(Agregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_estadoV1)
                    .addComponent(agregar_estadoD1)
                    .addComponent(agregar_desaparecidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Agregar1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar);
        Modificar.setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
            .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Estadistica.addTab("Modificar", Modificar);

        javax.swing.GroupLayout EliminarLayout = new javax.swing.GroupLayout(Eliminar);
        Eliminar.setLayout(EliminarLayout);
        EliminarLayout.setHorizontalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        EliminarLayout.setVerticalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        Estadistica.addTab("Eliminar", Eliminar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Estadistica)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Estadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void agregar_estadoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_estadoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_estadoDActionPerformed

    private void agregar_estadoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_estadoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_estadoVActionPerformed

    private void agregar_tipoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_tipoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_tipoCActionPerformed

    private void agregar_sexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_sexoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_sexoFActionPerformed

    private void agregar_sexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_sexoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_sexoMActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String nombre=agregar_nombre.getText();
        int edad = Integer.parseInt(agregar_edad.getText());
        String sexo="";
        String arma="";
        if (agregar_sexoM.isSelected()) {
            sexo = "Masculino";
        } else {
            sexo = "Femenino";
        }
        personas.add(new Personas(nombre,edad,sexo,arma));
        agregar_nombre.setText("");
        agregar_edad.setText("");
        agregar_sexoM.setSelected(true);
        agregar_sexoF.setSelected(false);
        agregar_tipoS.setSelected(true);
        agregar_tipoC.setSelected(false);
        agregar_tipoY.setSelected(false);
        agregar_estadoV.setSelected(true);
        agregar_estadoD.setSelected(false);
        agregar_desaparecidos.setText("");
        JOptionPane.showMessageDialog(this, "Persona Agregada!");
    }//GEN-LAST:event_jButton1MouseClicked

    private void agregar_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_edadActionPerformed

    private void agregar_estadoD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_estadoD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_estadoD1ActionPerformed

    private void agregar_estadoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_estadoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_estadoV1ActionPerformed

    private void agregar_tipoC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_tipoC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_tipoC1ActionPerformed

    private void agregar_sexoF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_sexoF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_sexoF1ActionPerformed

    private void agregar_sexoM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_sexoM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_sexoM1ActionPerformed

    private void agregar_edad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_edad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_edad1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String nombre=agregar_nombre.getText();
        int edad = Integer.parseInt(agregar_edad.getText());
        String sexo="";
        String arma="";
        if (agregar_sexoM.isSelected()) {
            sexo = "Masculino";
        } else {
            sexo = "Femenino";
        }
        personas.add(new Personas(nombre,edad,sexo,arma));
        agregar_nombre.setText("");
        agregar_edad.setText("");
        agregar_sexoM.setSelected(true);
        agregar_sexoF.setSelected(false);
        agregar_tipoS.setSelected(true);
        agregar_tipoC.setSelected(false);
        agregar_tipoY.setSelected(false);
        agregar_estadoV.setSelected(true);
        agregar_estadoD.setSelected(false);
        agregar_desaparecidos.setText("");
        JOptionPane.showMessageDialog(this, "Persona Modificada!");
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JPanel Agregar1;
    private javax.swing.JPanel Eliminar;
    private javax.swing.JTabbedPane Estadistica;
    private javax.swing.JPanel Estadisticas;
    private javax.swing.JPanel Modificar;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JLabel NombreLabel1;
    private javax.swing.JComboBox<String> agregar_arma;
    private javax.swing.JComboBox<String> agregar_arma1;
    private javax.swing.JTextField agregar_dano;
    private javax.swing.JTextField agregar_dano1;
    private javax.swing.JFormattedTextField agregar_desaparecidos;
    private javax.swing.JFormattedTextField agregar_desaparecidos1;
    private javax.swing.JFormattedTextField agregar_edad;
    private javax.swing.JFormattedTextField agregar_edad1;
    private javax.swing.JRadioButton agregar_estadoD;
    private javax.swing.JRadioButton agregar_estadoD1;
    private javax.swing.JRadioButton agregar_estadoV;
    private javax.swing.JRadioButton agregar_estadoV1;
    private javax.swing.JTextField agregar_nombre;
    private javax.swing.JTextField agregar_nombre1;
    private javax.swing.JRadioButton agregar_sexoF;
    private javax.swing.JRadioButton agregar_sexoF1;
    private javax.swing.JRadioButton agregar_sexoM;
    private javax.swing.JRadioButton agregar_sexoM1;
    private javax.swing.JRadioButton agregar_tipoC;
    private javax.swing.JRadioButton agregar_tipoC1;
    private javax.swing.JRadioButton agregar_tipoS;
    private javax.swing.JRadioButton agregar_tipoS1;
    private javax.swing.JRadioButton agregar_tipoY;
    private javax.swing.JRadioButton agregar_tipoY1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lista;
    // End of variables declaration//GEN-END:variables

private ArrayList<Personas> personas=new ArrayList();

}
